-- The original update targeted a deleted seed row and a column that was never
-- added to this table. Keep this migration as a no-op so Supabase can record
-- its version without writing seed data into production.
